# Generated by Django 3.1.7 on 2021-04-10 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name_of_user', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(null=True, upload_to='users')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_adoptant', models.BooleanField(default=False)),
                ('is_rescuer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='pets')),
                ('category', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10)),
                ('specie', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=10)),
                ('size', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=10)),
                ('years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_kid_friendly', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True)),
                ('is_dog_friendly', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True)),
                ('is_cat_friendly', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True)),
                ('vaccines', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True)),
                ('sterilized', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True)),
                ('payment', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Económico', 'Económico'), ('Croquetas', 'Croquetas')], max_length=10)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Pendiente', 'Pendiente'), ('Adoptado', 'Adoptado')], max_length=10)),
                ('user_adoptant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptant_user', to=settings.AUTH_USER_MODEL)),
                ('user_rescuer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescuer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSE', 'Close')], max_length=10, null=True)),
                ('applicant_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_user', to=settings.AUTH_USER_MODEL)),
                ('approver_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_user', to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pet', to='adopet_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=100)),
                ('address_ext_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address_int_num', models.CharField(max_length=6, null=True)),
                ('address_city', models.CharField(max_length=80)),
                ('address_zip_code', models.PositiveSmallIntegerField()),
                ('pet_owner', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4)),
                ('family_members', models.PositiveSmallIntegerField()),
                ('family_agreement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4)),
                ('document_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('user_applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to=settings.AUTH_USER_MODEL)),
                ('user_autorizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
