# Generated by Django 3.1.7 on 2021-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_of_user',
            field=models.CharField(max_length=30),
        ),
    ]
