# Generated by Django 3.1.7 on 2021-04-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=10)),
                ('specie', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_kid_friendly', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True)),
                ('is_dog_friendly', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True)),
                ('is_cat_friendly', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True)),
                ('vaccines', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True)),
                ('sterilized', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True)),
                ('payment', models.CharField(choices=[('NONE', 'None'), ('MONEY', 'Money'), ('FOOD', 'Food')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='adopet_app.role'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSE', 'Close')], max_length=10, null=True)),
                ('applicant_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_user', to='adopet_app.user')),
                ('approver_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_user', to='adopet_app.user')),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pet', to='adopet_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=100)),
                ('address_ext_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address_int_num', models.CharField(max_length=6, null=True)),
                ('address_city', models.CharField(max_length=80)),
                ('address_zip_code', models.PositiveSmallIntegerField()),
                ('pet_owner', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4)),
                ('family_members', models.PositiveSmallIntegerField()),
                ('family_agreement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4)),
                ('document_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('user_applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to='adopet_app.user')),
                ('user_autorizer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizer_user', to='adopet_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='user_adoptant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptant_user', to='adopet_app.user'),
        ),
        migrations.AddField(
            model_name='pet',
            name='user_rescuer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescuer_user', to='adopet_app.user'),
        ),
    ]
