# Generated by Django 3.1.7 on 2021-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0003_auto_20210331_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='static/images/pets/'),
        ),
    ]
