# Generated by Django 3.1.7 on 2021-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0004_auto_20210401_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='../static/images/pets'),
        ),
    ]
