# Generated by Django 3.1.7 on 2021-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0005_auto_20210401_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
