# Generated by Django 3.1.7 on 2021-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0006_auto_20210403_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_cat_friendly',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_dog_friendly',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_kid_friendly',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='payment',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Económico', 'Económico'), ('Croquetas', 'Croquetas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PENDIENTE', 'Pendiente'), ('ADOPTADO', 'Adoptado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sterilized',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccines',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=4, null=True),
        ),
    ]
