# Generated by Django 3.1.7 on 2021-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet_app', '0007_auto_20210403_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_cat_friendly',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_dog_friendly',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_kid_friendly',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='payment',
            field=models.CharField(choices=[('NONE', 'None'), ('MONEY', 'Money'), ('FOOD', 'Food')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sterilized',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccines',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
    ]
